### ISSUE TITLE
routing key

### ISSUE THREAD

**Issue by moodygit** [backstop/rabbit-mq-stress-tester#4]
Hi. Can I specify the routing key in stress test? Thx

**Comment by cstroe** [comment]
No, at the moment it seems that the [routing key](https://www.digitalocean.com/community/tutorials/how-to-deliver-messages-based-on-routing-keys-using-the-rabbitmq-and-puka-python-library) for messages cannot be specified.  @agocs might be able to shed some light on how to implement this functionality (it should be easy from looking at `producer.go`).

@moodygit, are you wanting to implement this?

**Comment by moodygit** [comment]
@cstroe yes, I'll wait. If you could implement it. Thank you

**Comment by agocs** [comment]
@cstroe Thanks for @-mentioning me. I unwatched this by accident.

@moodygit The easiest way to do this would be to add a `cli.StringFlag` in main.go, line 37, and to add `RoutingKey string` to the `ProducerConfig` in producer.go. I'll see if I have some time to make this happen soon. Remind me in a week if you don't hear back.

**Comment by moodygit** [comment]
@agocs sorry, but I am not very familiar with Go. After modifying I have build error. 
`/main.go:40: cannot use func literal (type func(*cli.Context) cli.StringFlag) as type func(*cli.Context) in assignment
./main.go:40: missing return at end of function
./producer.go:60: unknown amqp.Publishing field 'RoutingKey' in struct literal
`
Could You help, or better wait for patch?

**Comment by agocs** [comment]
@moodygit I'm working on it. Realized that I should specify an exchange too, and that the change touches both the producer and the consumer.

**Comment by moodygit** [comment]
@agocs specify the exchange is a good idea! Thank you for rapidly responded. I will wait for updates.

**Comment by agocs** [comment]
I made some progress this evening, but I can't manually test it yet. My cat is very insistent that I do not continue. Will keep working.

**Comment by moodygit** [comment]
@agocs Thx.

**Comment by cstroe** [comment]
@moodygit : The official repository has moved to https://github.com/agocs/rabbit-mq-stress-tester
@agocs: I'm sure you're aware of this issue, you might want to transition it over to your repo.
