### ISSUE TITLE
DEPRECATED Action signature

### ISSUE THREAD

**Issue by ltqdub** [backstop/rabbit-mq-stress-tester#5]
Hi,
I just ran your application on my Ubuntu Linux 15.10 against RabbitMQ 3.6.1 and I got the following message:

DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

I just wanted to let you just in case you haven't seen it yourself
otherwise, great application. thank you for sharing
Kind Regards
Bernhard

**Comment by agocs** [comment]
Thanks, Bernhard. I hadn't seen this myself, but I'll see if I can knock a fix out.
-Chris

**Comment by agocs** [comment]
@ltqdub I don't know if you saw, but @abrandemuehl fixed this one!

**Comment by cstroe** [comment]
Fixed in https://github.com/backstop/rabbit-mq-stress-tester/pull/6
